module.exports = {
  PENDING_SELLER: 'PENDING_SELLER',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  FUNDED: 'FUNDED',
  DISPUTED: 'DISPUTED',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};
